name: Publish Conan Packages

on:
  workflow_dispatch:

jobs:
  build-conan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Conan & yq
        run: |
          pip install conan
          sudo apt update
          sudo apt install -y yq

      - name: Build and export packages
        run: |
          mkdir -p pages/cwt-cucumber
          conan profile detect
          conan create ./all --name=cwt-cucumber --version=2.8
          mkdir -p pages/cwt-cucumber/2.8
          cp -r ~/.conan2/p/cwt-cucumber/* pages/cwt-cucumber/2.8/

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
